# Generated by Django 3.0.7 on 2020-07-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioList',
        ),
        migrations.AddField(
            model_name='portfolioticker',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Portfolio'),
        ),
    ]
