# Generated by Django 3.0.7 on 2020-07-24 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200723_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Watchlist',
        ),
        migrations.DeleteModel(
            name='PortfolioTicker',
        ),
        migrations.AddField(
            model_name='watchlistticker',
            name='watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Watchlist'),
        ),
    ]
