# Generated by Django 3.0.7 on 2020-07-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papertradetickers',
            old_name='amount_bought',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='papertradetickers',
            old_name='price_bought',
            new_name='price',
        ),
    ]
