# Generated by Django 3.0.7 on 2020-07-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0003_auto_20200724_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='money',
            field=models.FloatField(default=5000.0),
        ),
    ]
